### ISSUE TITLE
Add user profile page (get posts, whether current user follows them)

### ISSUE THREAD

**Issue by jarushford** [Cody-Price/BFit_fe#19]

**Comment by TimothyFell** [comment]
What data do you need from the backend for this? All posts created by current user, current_user's followers, current_user's user info? What you want?

**Comment by jarushford** [comment]
So for this we should already have their ID which gives us access to the endpoint we already have for name and image. I'm assuming we'll be able to get posts by a users ID, and then the last part depends on how we're keeping track of all of the people that a given user is following. So if we have a user ID, how with the backend schema will we get all of the users that they follow?
